version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    environment:
      - MONGODB_DATABASE=xxx
      - MONGODB_ROOT_PASSWORD=xxx
    volumes:
      - "/var/mongo/data:/bitnami/mongodb"
